/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sv.udb.forms;

import com.sv.udb.clases.Ejercicio;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Luis
 */
public class FrmEjercicio extends javax.swing.JFrame {

    /**
     * Creates new form FrmEjercicio
     */
     Ejercicio obj = new Ejercicio();
              // Aquí se pone en marcha el timer cada segundo. 
     Timer timer ;
     Timer timer2 ;
     Timer timer3 ;
//        TimerTask timerTask = new TimerTask() 
//     { 
//         public void run()  
//         { 
//           
//         } 
//     }; 
//           TimerTask timerTask2 = new TimerTask() 
//     { 
//         public void run()  
//         { 
//            
//             
//         } 
//     }; 
//              TimerTask timerTask3 = new TimerTask() 
//     { 
//         public void run()  
//         { 
//           obj.calculo3();
//          ImageIcon iconolbl3 = new ImageIcon(obj.getImagen3());
//        lblNum3.setIcon(iconolbl3);
//         } 
//     }; 

     
    public FrmEjercicio() {
        initComponents();
      this.setLocationRelativeTo(null);
      timer = new Timer (1000, new ActionListener()
      {
      @Override
      public void actionPerformed(ActionEvent e)
      {
        obj.calculo();
         ImageIcon iconolbl = new ImageIcon(obj.getImagen1());
        lblNum1.setIcon(iconolbl);
      }
      });
      
       timer2 = new Timer (1000, new ActionListener()
      {
      @Override
      public void actionPerformed(ActionEvent e)
      {
        obj.calculo2();
         ImageIcon iconolbl2 = new ImageIcon(obj.getImagen2());
        lblNum2.setIcon(iconolbl2);
      }
      });
        timer3 = new Timer (1000, new ActionListener()
      {
      @Override
      public void actionPerformed(ActionEvent e)
      {
         obj.calculo3();
        ImageIcon iconolbl3 = new ImageIcon(obj.getImagen3());
        lblNum3.setIcon(iconolbl3);
      }
      });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNum1 = new javax.swing.JLabel();
        lblNum2 = new javax.swing.JLabel();
        lblNum3 = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        btnParar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Corto// Luis Chévez");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Jugar"));

        lblNum1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sv/udb/Imagenes/1486845565_number_7_green.png"))); // NOI18N

        lblNum2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sv/udb/Imagenes/1486845565_number_7_green.png"))); // NOI18N

        lblNum3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sv/udb/Imagenes/1486845565_number_7_green.png"))); // NOI18N

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        btnParar.setText("Parar");
        btnParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPararActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnIniciar)
                        .addGap(18, 18, 18)
                        .addComponent(btnParar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNum1)
                        .addGap(18, 18, 18)
                        .addComponent(lblNum2)
                        .addGap(29, 29, 29)
                        .addComponent(lblNum3)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNum3)
                    .addComponent(lblNum2)
                    .addComponent(lblNum1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciar)
                    .addComponent(btnParar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed

     timer.start();
     timer2.start();
     timer3.start();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPararActionPerformed
        // TODO add your handling code here:
    timer.stop();
    timer2.stop();
    timer3.stop();
    if(obj.getNumero() == 7 && obj.getNumero2() == 7 && obj.getNumero3() == 7)
    {
    JOptionPane.showMessageDialog(this,"Felicidades usted a ganado" );
    obj.setContador(0);
    }
    }//GEN-LAST:event_btnPararActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEjercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEjercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEjercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEjercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEjercicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnParar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNum1;
    private javax.swing.JLabel lblNum2;
    private javax.swing.JLabel lblNum3;
    // End of variables declaration//GEN-END:variables
}
